# Generated by Django 4.2.11 on 2024-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('hunger', models.IntegerField()),
                ('energy', models.IntegerField()),
            ],
        ),
    ]
